stages:
  - androidbuild
  - androidtest

android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
    - Jacob_tag
  script:
    - echo "Running Android build task..."

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - Jacob_tag
  script:
    - echo "Running Android test task..."
