# test 25
stages:
  - androidbuild
  - androidtest 
  
android-build:
  image: afirefly/android-ci:java17
  stage: androidbuild
  tags:
   - Jacob_tag                   
  before_script:                    
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                  
    - ./gradlew build
  only:
    refs:
      - Jacob_CICD
    changes:
      - Frontend/**/*

android-test:
  image: afirefly/android-ci:java17
  stage: androidtest
  tags:
    - Jacob_tag                  
  before_script:                   
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend                  
    - ./gradlew test
  only:
    refs:
      - Jacob_CICD
    changes:
      - Frontend/**/*
